name: C++ CI

on:
  push:
    branches: ['**'] # NOTE: replace/update with appropriate branch name(s)
    tags: ['**']
  workflow_dispatch:
    inputs:
      build_type:
        description: Build type
        required: false
        default: 'Debug'
        type: choice
        options:
          - Debug
          - Release
          - RelWithDebInfo
          - MinSizeRel

env:
  BUILD_TYPE: ${{ inputs.build_type || 'Debug' }}
  EXECUTABLE_NAME: "oop"
  INPUT_FILENAME: "tastatura.txt"
  BIN_DIR: "bin"
  BUILD_DIR: "build"
  EXT_DIR: "ext"
  GEN_DIR: "generated"

defaults:
  run:
    shell: bash

jobs:
  cppcheck:
    name: "Cppcheck"
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    env:
      CPPCHECK_VER: "2.14.2"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run cppcheck
        uses: ./.github/actions/cppcheck

  clang-tidy:
    name: "Clang-Tidy"
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    env:
      CLANG_VER: 18
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run clang-tidy
        uses: ./.github/actions/clang-tidy

  build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 8
    permissions:
      attestations: write
      contents: write
      id-token: write

    env:
      CC: ${{ matrix.c }}
      CXX: ${{ matrix.cxx }}
      VSCMD_SKIP_SENDTELEMETRY: 1
      MINGW_VER: "13.3.0posix-11.0.1-msvcrt-r1/winlibs-x86_64-posix-seh-gcc-13.3.0-mingw-w64msvcrt-11.0.1-r1.7z"

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
            c: gcc-12
            cxx: g++-12
            name: "ASan: Ubuntu 22.04 GCC 12"
            cmake_flags: "-DUSE_ASAN=ON"
            cmake_generator: Ninja
            runs_asan: true
            asan_name: "-asan"

          - os: ubuntu-22.04
            c: gcc-12
            cxx: g++-12
            name: "Valgrind: Ubuntu 22.04 GCC 12"
            cmake_generator: Ninja
            runs_valgrind: true

          - os: macos-14
            c: clang
            cxx: clang++
            name: "macOS 14 Apple Clang 15"
            cmake_flags: "-DUSE_ASAN=OFF"
            runs_asan: false

          - os: macos-14
            c: gcc-13
            cxx: g++-13
            name: "macOS 14 GCC 13"

          - os: windows-2022
            c: cl
            cxx: cl
            name: "ASan: Windows 2022 MSVC 19.43"
            cmake_flags: "-DUSE_ASAN=ON"
            runs_asan: true

          - os: windows-2022
            c: gcc
            cxx: g++
            name: "Windows 2022 MinGW GCC 13"
            cmake_generator: Ninja

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set timestamp and zip name
        run: |
          echo "TIMESTAMP=$(date +%Y-%m-%d-%H-%M-%S)" >> ${GITHUB_ENV}
          echo "ZIP_NAME=$(echo "${GITHUB_REPOSITORY}_${{ env.BUILD_TYPE }}_${{ matrix.os }}_${{ matrix.cxx }}${{ matrix.asan_name }}" | sed 's|/|_|')" >> ${GITHUB_ENV}

      - name: Install packages
        uses: ./.github/actions/install-packages

      - name: Install CPR library (Release version)
        if: matrix.os == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev

          # Clone the CPR repository
          git clone https://github.com/libcpr/cpr.git
          cd cpr
          
          # Force Release build for CPR regardless of project build type
          mkdir build && cd build
          cmake .. -DCPR_USE_SYSTEM_CURL=ON -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON
          
          make -j$(nproc)
          sudo make install
          sudo ldconfig

      - name: Configure CMake with static curl
        if: matrix.os == 'ubuntu-22.04'
        uses: ./.github/actions/configure-cmake
        with:
          custom_flags: "${{ matrix.cmake_flags }} -DCURL_STATICLIB=ON -DCPR_FORCE_USE_SYSTEM_CURL=ON"
          warnings_as_errors: 'ON'

      - name: Configure CMake (non-Ubuntu)
        if: matrix.os != 'ubuntu-22.04'
        uses: ./.github/actions/configure-cmake
        with:
          custom_flags: ${{ matrix.cmake_flags }}
          warnings_as_errors: 'ON'

      - name: Build
        run: |
          bash ./scripts/cmake.sh build -c ${{ env.BUILD_TYPE }}

      - name: Install
        run: |
          bash ./scripts/cmake.sh install -c ${{ env.BUILD_TYPE }} -i artifacts

      - name: Move artifacts
        run: |
          mkdir ${{ env.ZIP_NAME }}
          shopt -s dotglob
          mv artifacts/${{ env.BIN_DIR }}/* ${{ env.ZIP_NAME }}
          ls -la ${{ env.ZIP_NAME }}

      - name: Process artifacts
        uses: ./.github/actions/process-artifacts

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ZIP_NAME }}_${{ env.TIMESTAMP }}
          include-hidden-files: true
          path: ${{ env.ZIP_NAME }}
          retention-days: 30

      - name: Find required libraries
        if: matrix.os == 'ubuntu-22.04'
        run: |
          echo "Looking for required libraries in the executable..."
          ldd ${{ env.ZIP_NAME }}/${{ env.EXECUTABLE_NAME }} || true
          
          echo "Updating LD_LIBRARY_PATH..."
          echo "LD_LIBRARY_PATH=/usr/local/lib:/usr/lib/x86_64-linux-gnu:${LD_LIBRARY_PATH}" >> ${GITHUB_ENV}

      - name: Create JSON file
        run: |
          cat > intrebari.json << 'EOF'
          {
          "intrebari": [
          {
          "intrebare": "Spuneți un motiv pentru care oamenii merg la mare.",
          "raspunsuri": [
          { "raspuns": "Să se relaxeze", "punctaj": 40 },
          { "raspuns": "Să înoate", "punctaj": 30 },
          { "raspuns": "Să se bronzeze", "punctaj": 20 },
          { "raspuns": "Să mănânce pește proaspăt", "punctaj": 10 }
          ]
          },
          {
          "intrebare": "Spuneți un lucru pe care românii îl fac când vine primăvara.",
          "raspunsuri": [
          { "raspuns": "Încep să îngrijească grădina", "punctaj": 35 },
          { "raspuns": "Ies în parc să se plimbe", "punctaj": 25 },
          { "raspuns": "Își schimbă garderoba", "punctaj": 20 },
          { "raspuns": "Planifică vacanțe", "punctaj": 15 },
          { "raspuns": "Fac curățenie generală", "punctaj": 5 }
          ]
          },
          {
          "intrebare": "Spuneți un aliment pe care românii îl mănâncă la micul dejun.",
          "raspunsuri": [
          { "raspuns": "Ouă", "punctaj": 30 },
          { "raspuns": "Pâine cu unt", "punctaj": 25 },
          { "raspuns": "Cereale", "punctaj": 20 },
          { "raspuns": "Șuncă", "punctaj": 15 },
          { "raspuns": "Brânză", "punctaj": 10 }
          ]
          },
          {
          "intrebare": "Spuneți un motiv pentru care oamenii folosesc telefonul mobil.",
          "raspunsuri": [
          { "raspuns": "Pentru a suna", "punctaj": 35 },
          { "raspuns": "Pentru a naviga pe internet", "punctaj": 30 },
          { "raspuns": "Pentru a folosi rețelele sociale", "punctaj": 20 },
          { "raspuns": "Pentru a face poze", "punctaj": 10 },
          { "raspuns": "Pentru a juca jocuri", "punctaj": 5 }
          ]
          },
          {
          "intrebare": "Spuneți un lucru pe care românii îl fac în timpul liber.",
          "raspunsuri": [
          { "raspuns": "Se uită la televizor", "punctaj": 40 },
          { "raspuns": "Ies cu prietenii", "punctaj": 25 },
          { "raspuns": "Citește cărți", "punctaj": 15 },
          { "raspuns": "Practică sport", "punctaj": 10 },
          { "raspuns": "Gătește", "punctaj": 10 }
          ]
          }
          ]
          }
          EOF
          
          # Copy to the directory with the executable
          cp intrebari.json ${{ env.ZIP_NAME }}/
          
          # Also create an empty tastatura.txt file (since this is your INPUT_FILENAME)
          touch tastatura.txt
          cp tastatura.txt ${{ env.ZIP_NAME }}/
          
          # List files to confirm
          ls -la ${{ env.ZIP_NAME }}/

      - name: Runtime checks
        uses: ./.github/actions/runtime-checks
        env:
          LD_LIBRARY_PATH: /usr/local/lib:/usr/lib/x86_64-linux-gnu:${{ env.LD_LIBRARY_PATH }}

      - name: Create release
        uses: ./.github/actions/create-release
        if: startsWith(github.ref, 'refs/tags/')